data_lake_dict = {
    "gene_info.parquet": "Comprehensive gene information.",
    "go-plus.json": "Gene ontology data for functional gene annotations.",
    "hp.obo": "Official HPO release in obographs format",
    "variant_table.parquet": "Annotated genetic variants table.",
    "genebass_missense_LC_filtered.pkl": "Filtered missense variants from GeneBass.",
    "genebass_pLoF_filtered.pkl": "Predicted loss-of-function variants from GeneBass.",
    "genebass_synonymous_filtered.pkl": "Filtered synonymous variants from GeneBass.",
    "omim.parquet": "Genetic disorders and associated genes from OMIM.",
    "genetic_interaction.parquet": "Genetic interactions between genes.",
    "DisGeNET.parquet": "Gene-disease associations from multiple sources.",
}

library_content_dict = {
    "pandas": "[Python Package] A fast, powerful, and flexible data analysis library.",
    "numpy": "[Python Package] The fundamental package for scientific computing.",
    "scipy": "[Python Package] A Python library for scientific and technical computing.",
    "scikit-learn": "[Python Package] A machine learning library.",
    "statsmodels": "[Python Package] A Python module for statistical modeling.",
    "pymc3": "[Python Package] A Python package for Bayesian statistical modeling.",
    "tqdm": "[Python Package] A fast, extensible progress bar.",
    "joblib": "[Python Package] A set of tools to provide lightweight pipelining.",
    "h5py": "[Python Package] A Python interface to the HDF5 binary data format.",
    "tiledb": "[Python Package] engine for storing large-scale genomic data.",
    "tiledbsoma": "[Python Package] A library for working with the SOMA format.",
    "matplotlib": "[Python Package] A comprehensive library for visualizations.",
    "seaborn": "[Python Package] A statistical data visualization library.",
    "biopython": "[Python Package] A set of tools for biological computation.",
    "googlesearch-python": "[Python Package] A library for performing Google searches.",
    "pymed": "[Python Package] A Python library for accessing PubMed articles.",
    "arxiv": "[Python Package] A Python wrapper for the arXiv API.",
    "scholarly": "[Python Package] A module to retrieve Google Scholar info.",
    "PyPDF2": "[Python Package] A library for working with PDF files.",
    "reportlab": "[Python Package] Creation of PDF documents.",
    "plink": "[CLI Tool] toolkit for genome association studies.",
    "plink2": "[CLI Tool] toolkit for genome association studies.",
    "gcta64": "[CLI Tool] Genome-wide Complex Trait Analysis (GCTA) tool.",
    "tskit": "[Python Package] Handling tree sequences.",
    "msprime": "[Python Package] Simulation of genetic variation.",
    "cyvcf2": "[Python Package] Fast parsing of VCF files.",
    "pyliftover": "[Python Package] A Python implementation of UCSC liftOver tool.",
    "pysam": "[Python Package] A Python module for reading, manipulating genomic data sets.",
    "bedtools": "[CLI Tool] powerful toolset for genome arithmetic.",
    "cooler": "[Python Package] Storage and analysis of Hi-C data.",
    "pyranges": "[Python Package] A Python package for interval manipulation with a pandas-like interface.",
    "umap-learn": "[Python Package] Uniform Manifold Approximation and Projection, a dimension reduction technique.",
    "clusterProfiler": "[R Package] A package for statistical analysis and visualization of functional profiles for genes and gene clusters.",
    "dplyr": "[R Package] A grammar of data manipulation.",
    "ggplot2": "[R Package] A system for declaratively creating graphics.",
    "readr": "[R Package] A fast and friendly way to read rectangular data like CSV and TSV.",
    "tidyr": "[R Package] A package that helps create tidy data.",
}
