data_lake_dict = {
    "gene_info.parquet": "Comprehensive gene information.",
    "go-plus.json": "Gene ontology data for functional gene annotations.",
    "hp.obo": "Official HPO release in obographs format",
    "proteinatlas.tsv": "Protein expression data from Human Protein Atlas.",
}

library_content_dict = {
    "pandas": "[Python Package] A fast, powerful, and flexible data analysis library.",
    "numpy": "[Python Package] The fundamental package for scientific computing.",
    "scipy": "[Python Package] A Python library for scientific and technical computing.",
    "scikit-learn": "[Python Package] A machine learning library.",
    "statsmodels": "[Python Package] A Python module for statistical modeling.",
    "pymc3": "[Python Package] A Python package for Bayesian statistical modeling.",
    "tqdm": "[Python Package] A fast, extensible progress bar.",
    "joblib": "[Python Package] A set of tools to provide lightweight pipelining.",
    "h5py": "[Python Package] A Python interface to the HDF5 binary data format.",
    "tiledb": "[Python Package] engine for storing large-scale genomic data.",
    "tiledbsoma": "[Python Package] A library for working with the SOMA format.",
    "matplotlib": "[Python Package] A comprehensive library for visualizations.",
    "seaborn": "[Python Package] A statistical data visualization library.",
    "biopython": "[Python Package] A set of tools for biological computation.",
    "googlesearch-python": "[Python Package] A library for performing Google searches.",
    "pymed": "[Python Package] A Python library for accessing PubMed articles.",
    "arxiv": "[Python Package] A Python wrapper for the arXiv API.",
    "scholarly": "[Python Package] A module to retrieve Google Scholar info.",
    "PyPDF2": "[Python Package] A library for working with PDF files.",
    "reportlab": "[Python Package] Creation of PDF documents.",
    "openmm": "[Python Package] A toolkit for molecular simulation.",
    "cryosparc-tools": "[Python Package] Tools for working with cryoSPARC.",
    "lazyslide": "[Python Package] A Python framework for whole slide image analysis.",
    "trackpy": "[Python Package] Particle tracking in images and video.",
    "scikit-image": "[Python Package] A collection of algorithms for image processing.",
    "opencv-python": "[Python Package] OpenCV library for computer vision tasks.",
    "biotite": "[Python Package] A comprehensive library for computational molecular biology.",
    "pdbfixer": "A Python package for fixing problems in PDB files.",
    "cellpose": "[Python Package] Cell segmentation in microscopy images.",
    "biopandas": "[Python Package] A package that provides pandas DataFrames for working with molecular structures and biological data.",
    "hmmlearn": "[Python Package] Hidden Markov model analysis.",
    "pykalman": "[Python Package] Kalman filter and smoother implementation.",
}
