data_lake_dict = {
    "gene_info.parquet": "Comprehensive gene information.",
    "go-plus.json": "Gene ontology data for functional gene annotations.",
    "hp.obo": "Official HPO release in obographs format",
    "sgRNA_KO_SP_human.txt": "sgRNA knockout data for human.",
    "sgRNA_KO_SP_mouse.txt": "sgRNA knockout data for mouse.",
    "DepMap_CRISPRGeneEffect.csv": "Genome-wide CRISPR gene effect estimates for cancer cell lines, including all DepMap models.",
    "DepMap_CRISPRGeneDependency.csv": "Gene dependency probability estimates for cancer cell lines, including all DepMap models.",
}

library_content_dict = {
    "pandas": "[Python Package] A fast, powerful, and flexible data analysis library.",
    "numpy": "[Python Package] The fundamental package for scientific computing.",
    "scipy": "[Python Package] A Python library for scientific and technical computing.",
    "scikit-learn": "[Python Package] A machine learning library.",
    "statsmodels": "[Python Package] A Python module for statistical modeling.",
    "pymc3": "[Python Package] A Python package for Bayesian statistical modeling.",
    "tqdm": "[Python Package] A fast, extensible progress bar.",
    "joblib": "[Python Package] A set of tools to provide lightweight pipelining.",
    "h5py": "[Python Package] A Python interface to the HDF5 binary data format.",
    "tiledb": "[Python Package] engine for storing large-scale genomic data.",
    "tiledbsoma": "[Python Package] A library for working with the SOMA format.",
    "matplotlib": "[Python Package] A comprehensive library for visualizations.",
    "seaborn": "[Python Package] A statistical data visualization library.",
    "biopython": "[Python Package] A set of tools for biological computation.",
    "googlesearch-python": "[Python Package] A library for performing Google searches.",
    "pymed": "[Python Package] A Python library for accessing PubMed articles.",
    "arxiv": "[Python Package] A Python wrapper for the arXiv API.",
    "scholarly": "[Python Package] A module to retrieve Google Scholar info.",
    "PyPDF2": "[Python Package] A library for working with PDF files.",
    "reportlab": "[Python Package] Creation of PDF documents.",
    "plannotate": "[CLI Tool] tool for annotating plasmid sequences.",
    "viennarna": "[Python Package] RNA secondary structure prediction.",
    "mageck": "[Python Package] Analysis of CRISPR screen data.",
    "Homer": "[CLI Tool] Motif discovery and next-gen sequencing분석.",
    "biopandas": "[Python Package] A package that provides pandas DataFrames for working with molecular structures and biological data.",
    "cooler": "[Python Package] Storage and analysis of Hi-C data.",
    "pyranges": "[Python Package] A Python package for interval manipulation with a pandas-like interface.",
    "clusterProfiler": "[R Package] A package for statistical analysis and visualization of functional profiles for genes and gene clusters.",
}
