_wandb:
    value:
        cli_version: 0.24.2
        e:
            zk4mqdhl6w6r892ckspyeco70j38ru1j:
                args:
                    - --benchmark
                    - biomni_eval1
                    - --tasks
                    - rare_disease_diagnosis
                    - --agent-timeout-seconds
                    - "600"
                    - --max-instances
                    - "5"
                codePath: biomni/eval/run_eval.py
                codePathLocal: biomni/eval/run_eval.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "502392610816"
                        used: "258007519232"
                email: cwj6705@dankook.ac.kr
                executable: /home/aiffel07/anaconda3/envs/biomni_e1/bin/python
                git:
                    commit: c1152230ff158ae7e2cd992b50fcad53b698af16
                    remote: https://github.com/snap-stanford/Biomni.git
                gpu: NVIDIA GeForce RTX 2070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2304
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070
                      uuid: GPU-982ae532-ddc6-5f0b-37db-4d8a2e608be4
                host: aiffel07-GE75-Raider-10SF
                memory:
                    total: "16571457536"
                os: Linux-6.8.0-100-generic-x86_64-with-glibc2.39
                program: /home/aiffel07/wonjin/Biomni/biomni/eval/run_eval.py
                python: CPython 3.11.14
                root: /home/aiffel07/wonjin/Biomni
                startedAt: "2026-02-22T11:46:58.878855Z"
                writerId: zk4mqdhl6w6r892ckspyeco70j38ru1j
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 49
                - 86
                - 95
                - 105
            "2":
                - 1
                - 11
                - 49
                - 86
                - 95
                - 105
            "3":
                - 2
                - 16
            "4": 3.11.14
            "5": 0.24.2
            "6": 5.1.0
            "10":
                - 20
            "12": 0.24.2
            "13": linux-x86_64
agent_timeout_seconds:
    value: 600
benchmark:
    value: biomni_eval1
benchmark_id:
    value: biomni_eval1
db_path:
    value: biomni_eval.db
llm:
    value: null
max_instances:
    value: 5
no_wandb:
    value: false
path:
    value: null
resume:
    value: false
resume_experiment_id:
    value: null
self_critic:
    value: false
split:
    value: val
tasks:
    value:
        - rare_disease_diagnosis
test_time_scale_round:
    value: 0
timestamp:
    value: 1.7717608217837114e+09
wandb_entity:
    value: null
wandb_name:
    value: null
wandb_project:
    value: biomni-eval
