data_lake_dict = {
    "gene_info.parquet": "Comprehensive gene information.",
    "go-plus.json": "Gene ontology data for functional gene annotations.",
    "hp.obo": "Official HPO release in obographs format",
    "czi_census_datasets_v4.parquet": "Datasets from the Chan Zuckerberg Initiative's Cell Census.",
    "marker_celltype.parquet": "Cell type marker genes for identification.",
    "DepMap_Model.csv": "Metadata describing all cancer models/cell lines which are referenced by a dataset contained within the DepMap portal.",
    "DepMap_CRISPRGeneEffect.csv": "Genome-wide CRISPR gene effect estimates for cancer cell lines, including all DepMap models.",
    "DepMap_CRISPRGeneDependency.csv": "Gene dependency probability estimates for cancer cell lines, including all DepMap models.",
    "msigdb_human_c8_celltype_signature_geneset.parquet": "Cell type signatures from MSigDB.",
    "mousemine_m8_celltype_signature_geneset.parquet": "Cell type signature gene sets from MouseMine.",
}

library_content_dict = {
    "pandas": "[Python Package] A fast, powerful, and flexible data analysis library.",
    "numpy": "[Python Package] The fundamental package for scientific computing.",
    "scipy": "[Python Package] A Python library for scientific and technical computing.",
    "scikit-learn": "[Python Package] A machine learning library.",
    "statsmodels": "[Python Package] A Python module for statistical modeling.",
    "pymc3": "[Python Package] A Python package for Bayesian statistical modeling.",
    "tqdm": "[Python Package] A fast, extensible progress bar.",
    "joblib": "[Python Package] A set of tools to provide lightweight pipelining.",
    "h5py": "[Python Package] A Python interface to the HDF5 binary data format.",
    "tiledb": "[Python Package] engine for storing large-scale genomic data.",
    "tiledbsoma": "[Python Package] A library for working with the SOMA format.",
    "matplotlib": "[Python Package] A comprehensive library for visualizations.",
    "seaborn": "[Python Package] A statistical data visualization library.",
    "biopython": "[Python Package] A set of tools for biological computation.",
    "googlesearch-python": "[Python Package] A library for performing Google searches.",
    "pymed": "[Python Package] A Python library for accessing PubMed articles.",
    "arxiv": "[Python Package] A Python wrapper for the arXiv API.",
    "scholarly": "[Python Package] A module to retrieve Google Scholar info.",
    "PyPDF2": "[Python Package] A library for working with PDF files.",
    "reportlab": "[Python Package] Creation of PDF documents.",
    "scanpy": "[Python Package] A scalable toolkit for analyzing single-cell gene expression data.",
    "anndata": "[Python Package] A Python package for handling annotated data matrices.",
    "mudata": "[Python Package] A Python package for multimodal data storage and manipulation.",
    "scvelo": "[Python Package] A tool for RNA velocity analysis.",
    "scrublet": "[Python Package] A tool for detecting doublets in single-cell RNA-seq data.",
    "cellxgene-census": "[Python Package] A tool for accessing and analyzing the CellxGene Census.",
    "harmony-pytorch": "[Python Package] A PyTorch implementation of the Harmony algorithm.",
    "loompy": "A Python implementation of the Loom file format.",
    "pyscenic": "[Python Package] Analysis of gene regulatory networks.",
    "arboreto": "A Python package for inferring gene regulatory networks.",
    "flowkit": "[Python Package] Toolkit for processing flow cytometry data.",
    "FlowIO": "A Python package for reading/writing flow cytometry data.",
    "FlowUtils": "Utilities for flow cytometry data.",
    "cellpose": "[Python Package] Cell segmentation in microscopy images.",
    "trackpy": "[Python Package] Particle tracking in images and video.",
    "scikit-image": "[Python Package] A collection of algorithms for image processing.",
    "cooler": "[Python Package] Storage and analysis of Hi-C data.",
    "faiss-cpu": "[Python Package] A library for efficient similarity search and clustering of dense vectors.",
    "umap-learn": "[Python Package] Uniform Manifold Approximation and Projection, a dimension reduction technique.",
    "Matrix": "[R Package] A package that provides classes and methods for dense and sparse matrices.",
    "fcsparser": "[CLI Tool] A command-line tool for parsing and analyzing flow cytometry standard (FCS) files.",
}
