_wandb:
    value:
        cli_version: 0.24.2
        e:
            fif4760kg1ve2csghtdcnekm3zp3uh1v:
                args:
                    - --benchmark
                    - biomni_eval1
                    - --resume
                    - --resume-experiment-id
                    - "15"
                    - --agent-timeout-seconds
                    - "300"
                codePath: biomni/eval/run_eval.py
                codePathLocal: biomni/eval/run_eval.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "502392610816"
                        used: "276443160576"
                email: cwj6705@dankook.ac.kr
                executable: /home/aiffel07/anaconda3/envs/biomni_e1/bin/python
                git:
                    commit: 370afc51ff208ca8132e0c676e1ca2eaf19c1819
                    remote: https://github.com/snap-stanford/Biomni.git
                gpu: NVIDIA GeForce RTX 2070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2304
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070
                      uuid: GPU-982ae532-ddc6-5f0b-37db-4d8a2e608be4
                host: aiffel07-GE75-Raider-10SF
                memory:
                    total: "16571445248"
                os: Linux-6.8.0-100-generic-x86_64-with-glibc2.39
                program: /home/aiffel07/wonjin/Biomni/biomni/eval/run_eval.py
                python: CPython 3.11.14
                root: /home/aiffel07/wonjin/Biomni
                startedAt: "2026-02-19T07:28:25.706385Z"
                writerId: fif4760kg1ve2csghtdcnekm3zp3uh1v
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 49
                - 86
                - 95
                - 105
            "2":
                - 1
                - 11
                - 49
                - 86
                - 95
                - 105
            "3":
                - 16
            "4": 3.11.14
            "5": 0.24.2
            "6": 5.1.0
            "10":
                - 20
            "12": 0.24.2
            "13": linux-x86_64
agent_timeout_seconds:
    value: 300
benchmark:
    value: biomni_eval1
benchmark_id:
    value: biomni_eval1
db_path:
    value: biomni_eval.db
llm:
    value: null
max_instances:
    value: null
no_wandb:
    value: false
path:
    value: null
resume:
    value: true
resume_experiment_id:
    value: 15
self_critic:
    value: false
split:
    value: val
tasks:
    value:
        - crispr_delivery
        - gwas_causal_gene_gwas_catalog
        - gwas_causal_gene_opentargets
        - gwas_causal_gene_pharmaprojects
        - gwas_variant_prioritization
        - lab_bench_dbqa
        - lab_bench_seqqa
        - patient_gene_detection
        - rare_disease_diagnosis
        - screen_gene_retrieval
test_time_scale_round:
    value: 0
timestamp:
    value: 1.7714861084091911e+09
wandb_entity:
    value: null
wandb_name:
    value: null
wandb_project:
    value: biomni-eval
