data_lake_dict = {
    'gene_info.parquet': 'Comprehensive gene information.',
    'go-plus.json': 'Gene ontology data for functional gene annotations.',
    'hp.obo': 'Official HPO release in obographs format',
    'synthetic_growth_defect.parquet': 'Synthetic growth defects from genetic interactions.',
    'synthetic_lethality.parquet': 'Synthetic lethal interactions.',
    'synthetic_rescue.parquet': 'Genetic interactions rescuing phenotypes.',
    'dosage_growth_defect.parquet': 'Gene dosage changes affecting growth.',
    'genetic_interaction.parquet': 'Genetic interactions between genes.',
}

library_content_dict = {
    'pandas': '[Python Package] A fast, powerful, and flexible data analysis library.',
    'numpy': '[Python Package] The fundamental package for scientific computing.',
    'scipy': '[Python Package] A Python library for scientific and technical computing.',
    'scikit-learn': '[Python Package] A machine learning library.',
    'statsmodels': '[Python Package] A Python module for statistical modeling.',
    'pymc3': '[Python Package] A Python package for Bayesian statistical modeling.',
    'tqdm': '[Python Package] A fast, extensible progress bar.',
    'joblib': '[Python Package] A set of tools to provide lightweight pipelining.',
    'h5py': '[Python Package] A Python interface to the HDF5 binary data format.',
    'tiledb': '[Python Package] engine for storing large-scale genomic data.',
    'tiledbsoma': '[Python Package] A library for working with the SOMA format.',
    'matplotlib': '[Python Package] A comprehensive library for visualizations.',
    'seaborn': '[Python Package] A statistical data visualization library.',
    'biopython': '[Python Package] A set of tools for biological computation.',
    'googlesearch-python': '[Python Package] A library for performing Google searches.',
    'pymed': '[Python Package] A Python library for accessing PubMed articles.',
    'arxiv': '[Python Package] A Python wrapper for the arXiv API.',
    'scholarly': '[Python Package] A module to retrieve Google Scholar info.',
    'PyPDF2': '[Python Package] A library for working with PDF files.',
    'reportlab': '[Python Package] Creation of PDF documents.',
    'cobra': '[Python Package] Constraint-based modeling of metabolic networks.',
    'python-libsbml': '[Python Package] Working with SBML files.',
    'arboreto': 'A Python package for inferring gene regulatory networks.',
    'optlang': 'A Python package for modeling optimization problems.',
    'viennarna': '[Python Package] RNA secondary structure prediction.',
    'plannotate': '[CLI Tool] tool for annotating plasmid sequences.',
}
