data_lake_dict = {
    "gene_info.parquet": "Comprehensive gene information.",
    "go-plus.json": "Gene ontology data for functional gene annotations.",
    "hp.obo": "Official HPO release in obographs format",
    "McPAS-TCR.parquet": "T-cell receptor sequences and specificity data from McPAS database.",
    "msigdb_human_c7_immunologic_signature_geneset.parquet": "Immunologic signatures from MSigDB.",
    "gtex_tissue_gene_tpm.parquet": "Gene expression (TPM) across human tissues from GTEx.",
}

library_content_dict = {
    "pandas": "[Python Package] A fast, powerful, and flexible data analysis library.",
    "numpy": "[Python Package] The fundamental package for scientific computing.",
    "scipy": "[Python Package] A Python library for scientific and technical computing.",
    "scikit-learn": "[Python Package] A machine learning library.",
    "statsmodels": "[Python Package] A Python module for statistical modeling.",
    "pymc3": "[Python Package] A Python package for Bayesian statistical modeling.",
    "tqdm": "[Python Package] A fast, extensible progress bar.",
    "joblib": "[Python Package] A set of tools to provide lightweight pipelining.",
    "h5py": "[Python Package] A Python interface to the HDF5 binary data format.",
    "tiledb": "[Python Package] engine for storing large-scale genomic data.",
    "tiledbsoma": "[Python Package] A library for working with the SOMA format.",
    "matplotlib": "[Python Package] A comprehensive library for visualizations.",
    "seaborn": "[Python Package] A statistical data visualization library.",
    "biopython": "[Python Package] A set of tools for biological computation.",
    "googlesearch-python": "[Python Package] A library for performing Google searches.",
    "pymed": "[Python Package] A Python library for accessing PubMed articles.",
    "arxiv": "[Python Package] A Python wrapper for the arXiv API.",
    "scholarly": "[Python Package] A module to retrieve Google Scholar info.",
    "PyPDF2": "[Python Package] A library for working with PDF files.",
    "reportlab": "[Python Package] Creation of PDF documents.",
    "flowkit": "[Python Package] Toolkit for processing flow cytometry data.",
    "FlowIO": "A Python package for reading/writing flow cytometry data.",
    "scanpy": "[Python Package] A scalable toolkit for analyzing single-cell gene expression data.",
    "fanc": "[Python Package] Analysis of chromatin conformation data.",
    "hmmlearn": "[Python Package] Hidden Markov model analysis.",
    "pykalman": "[Python Package] Kalman filter and smoother implementation.",
    "umap-learn": "[Python Package] Uniform Manifold Approximation and Projection, a dimension reduction technique.",
    "Matrix": "[R Package] A package that provides classes and methods for dense and sparse matrices.",
    "ggplot2": "[R Package] A system for declaratively creating graphics.",
    "fcsparser": "[CLI Tool] A command-line tool for parsing and analyzing flow cytometry standard (FCS) files.",
}
