data_lake_dict = {
    "gene_info.parquet": "Comprehensive gene information.",
    "go-plus.json": "Gene ontology data for functional gene annotations.",
    "hp.obo": "Official HPO release in obographs format",
    "BindingDB_All_202409.tsv": "Measured binding affinities between proteins and small molecules for drug discovery.",
    "broad_repurposing_hub_molecule_with_smiles.parquet": "Molecules from Broad Institute's Drug Repurposing Hub with SMILES annotations.",
    "broad_repurposing_hub_phase_moa_target_info.parquet": "Drug phases, mechanisms of action, and target information from Broad Institute.",
    "enamine_cloud_library_smiles.pkl": "Compounds from Enamine REAL library with SMILES annotations.",
    "evebio_assay_table.csv": "Assay metadata with one row per assay from EveBio pharmome mapping.",
    "evebio_bundle_table.csv": "Target subfamily bundles used for screening-to-profiling progression.",
    "evebio_compound_table.csv": "Compound metadata with common identifiers from EveBio screening.",
    "evebio_control_table.csv": "Control datapoints for all screening and profiling plates.",
    "evebio_detailed_result_table.csv": "Expanded results on evebio_summary_result_table with curve fit parameters and phase categories.",
    "evebio_observed_points_table.csv": "Raw observed datapoints from all screening and profiling experiments.",
    "evebio_summary_result_table.csv": "Succinct summary of results for each assay-compound combination.",
    "evebio_target_table.csv": "Target metadata with common identifiers from EveBio screening.",
    "txgnn_name_mapping.pkl": "Name mapping for TXGNN.",
    "txgnn_prediction.pkl": "Prediction data for TXGNN.",
    "ddinter_alimentary_tract_metabolism.csv": "Drug-drug interactions for alimentary tract and metabolism drugs from DDInter 2.0 database.",
    "ddinter_antineoplastic.csv": "Drug-drug interactions for antineoplastic and immunomodulating agents from DDInter 2.0 database.",
    "ddinter_antiparasitic.csv": "Drug-drug interactions for antiparasitic products from DDInter 2.0 database.",
    "ddinter_blood_organs.csv": "Drug-drug interactions for blood and blood forming organs drugs from DDInter 2.0 database.",
    "ddinter_dermatological.csv": "Drug-drug interactions for dermatological drugs from DDInter 2.0 database.",
    "ddinter_hormonal.csv": "Drug-drug interactions for systemic hormonal preparations from DDInter 2.0 database.",
    "ddinter_respiratory.csv": "Drug-drug interactions for respiratory system drugs from DDInter 2.0 database.",
    "ddinter_various.csv": "Drug-drug interactions for various drugs from DDInter 2.0 database.",
}

library_content_dict = {
    "pandas": "[Python Package] A fast, powerful, and flexible data analysis library.",
    "numpy": "[Python Package] The fundamental package for scientific computing.",
    "scipy": "[Python Package] A Python library for scientific and technical computing.",
    "scikit-learn": "[Python Package] A machine learning library.",
    "statsmodels": "[Python Package] A Python module for statistical modeling.",
    "pymc3": "[Python Package] A Python package for Bayesian statistical modeling.",
    "tqdm": "[Python Package] A fast, extensible progress bar.",
    "joblib": "[Python Package] A set of tools to provide lightweight pipelining.",
    "h5py": "[Python Package] A Python interface to the HDF5 binary data format.",
    "tiledb": "[Python Package] engine for storing large-scale genomic data.",
    "tiledbsoma": "[Python Package] A library for working with the SOMA format.",
    "matplotlib": "[Python Package] A comprehensive library for visualizations.",
    "seaborn": "[Python Package] A statistical data visualization library.",
    "biopython": "[Python Package] A set of tools for biological computation.",
    "googlesearch-python": "[Python Package] A library for performing Google searches.",
    "pymed": "[Python Package] A Python library for accessing PubMed articles.",
    "arxiv": "[Python Package] A Python wrapper for the arXiv API.",
    "scholarly": "[Python Package] A module to retrieve Google Scholar info.",
    "PyPDF2": "[Python Package] A library for working with PDF files.",
    "reportlab": "[Python Package] Creation of PDF documents.",
    "rdkit": "[Python Package] cheminformatics and machine learning tools.",
    "openbabel": "[Python Package] A chemical toolbox.",
    "deeppurpose": "[Python Package] A deep learning library for drug-target interaction prediction.",
    "pyscreener": "[Python Package] A Python package for virtual screening.",
    "pytdc": "[Python Package] A Python package for Therapeutics Data Commons.",
    "vina": "[CLI Tool] open-source program for molecular docking.",
    "ADFR": "AutoDock for Receptors suite for molecular docking.",
    "autosite": "[CLI Tool] binding site detection tool.",
    "descriptastorus": "[Python Package] A library for computing molecular descriptors.",
    "hyperopt": "[Python Package] A Python library for optimizing hyperparameters of machine learning algorithms.",
    "clusterProfiler": "[R Package] A package for statistical analysis and visualization of functional profiles for genes and gene clusters.",
    "dplyr": "[R Package] A grammar of data manipulation.",
}
