data_lake_dict = {
    "gene_info.parquet": "Comprehensive gene information.",
    "go-plus.json": "Gene ontology data for functional gene annotations.",
    "hp.obo": "Official HPO release in obographs format",
    "gtex_tissue_gene_tpm.parquet": "Gene expression (TPM) across human tissues from GTEx.",
    "DepMap_OmicsExpressionProteinCodingGenesTPMLogp1.csv": "Gene expression in TPMs for cancer cell lines, including all DepMap models.",
    "czi_census_datasets_v4.parquet": "Datasets from the Chan Zuckerberg Initiative's Cell Census.",
    "marker_celltype.parquet": "Cell type marker genes for identification.",
    "miRDB_v6.0_results.parquet": "Predicted microRNA targets from miRDB.",
    "miRTarBase_microRNA_target_interaction.parquet": "Experimentally validated microRNA-target interactions from miRTarBase.",
    "miRTarBase_MicroRNA_Target_Sites.parquet": "Binding sites of microRNAs on target genes from miRTarBase.",
    "miRTarBase_microRNA_target_interaction_pubmed_abtract.txt": "PubMed abstracts for microRNA-target interactions in miRTarBase.",
    "mousemine_m1_positional_geneset.parquet": "Positional gene sets from MouseMine.",
    "mousemine_m2_curated_geneset.parquet": "Curated gene sets from MouseMine.",
    "mousemine_m3_regulatory_target_geneset.parquet": "Regulatory target gene sets from MouseMine.",
    "mousemine_m5_ontology_geneset.parquet": "Ontology-based gene sets from MouseMine.",
    "mousemine_m8_celltype_signature_geneset.parquet": "Cell type signature gene sets from MouseMine.",
    "mousemine_mh_hallmark_geneset.parquet": "Hallmark gene sets from MouseMine.",
    "msigdb_human_c1_positional_geneset.parquet": "Human positional gene sets from MSigDB.",
    "msigdb_human_c2_curated_geneset.parquet": "Curated human gene sets from MSigDB.",
    "msigdb_human_c3_regulatory_target_geneset.parquet": "Regulatory target gene sets from MSigDB.",
    "msigdb_human_c3_subset_transcription_factor_targets_from_GTRD.parquet": "Transcription factor targets from GTRD/MSigDB.",
    "msigdb_human_c4_computational_geneset.parquet": "Computationally derived gene sets from MSigDB.",
    "msigdb_human_c5_ontology_geneset.parquet": "Ontology-based gene sets from MSigDB.",
    "msigdb_human_c6_oncogenic_signature_geneset.parquet": "Oncogenic signatures from MSigDB.",
    "msigdb_human_c7_immunologic_signature_geneset.parquet": "Immunologic signatures from MSigDB.",
    "msigdb_human_c8_celltype_signature_geneset.parquet": "Cell type signatures from MSigDB.",
    "msigdb_human_h_hallmark_geneset.parquet": "Hallmark gene sets from MSigDB.",
}

library_content_dict = {
    "pandas": "[Python Package] A fast, powerful, and flexible data analysis library.",
    "numpy": "[Python Package] The fundamental package for scientific computing.",
    "scipy": "[Python Package] A Python library for scientific and technical computing.",
    "scikit-learn": "[Python Package] A machine learning library.",
    "statsmodels": "[Python Package] A Python module for statistical modeling.",
    "pymc3": "[Python Package] A Python package for Bayesian statistical modeling.",
    "tqdm": "[Python Package] A fast, extensible progress bar.",
    "joblib": "[Python Package] A set of tools to provide lightweight pipelining.",
    "h5py": "[Python Package] A Python interface to the HDF5 binary data format.",
    "tiledb": "[Python Package] engine for storing large-scale genomic data.",
    "tiledbsoma": "[Python Package] A library for working with the SOMA format.",
    "matplotlib": "[Python Package] A comprehensive library for visualizations.",
    "seaborn": "[Python Package] A statistical data visualization library.",
    "biopython": "[Python Package] A set of tools for biological computation.",
    "googlesearch-python": "[Python Package] A library for performing Google searches.",
    "pymed": "[Python Package] A Python library for accessing PubMed articles.",
    "arxiv": "[Python Package] A Python wrapper for the arXiv API.",
    "scholarly": "[Python Package] A module to retrieve Google Scholar info.",
    "PyPDF2": "[Python Package] A library for working with PDF files.",
    "reportlab": "[Python Package] Creation of PDF documents.",
    "samtools": "[CLI Tool] A suite of programs for high-throughput sequencing data.",
    "bedtools": "[CLI Tool] powerful toolset for genome arithmetic.",
    "pybedtools": "[Python Package] A Python wrapper for Aaron Quinlan's BEDTools programs.",
    "bwa": "[CLI Tool] Burrows-Wheeler Aligner.",
    "bowtie2": "[CLI Tool] tool for aligning sequencing reads.",
    "pysam": "[Python Package] A Python module for reading, manipulating genomic data sets.",
    "pyfaidx": "[Python Package] A Python package for random access to FASTA files.",
    "pyBigWig": "A Python library for accessing bigWig and bigBed files.",
    "macs2": "[CLI Tool] Model-based Analysis of ChIP-Seq data.",
    "fastqc": "[CLI Tool] quality control tool for high throughput sequence data.",
    "trimmomatic": "[CLI Tool] read trimming tool for Illumina NGS data.",
    "scanpy": "[Python Package] A scalable toolkit for analyzing single-cell gene expression data.",
    "anndata": "[Python Package] A Python package for handling annotated data matrices.",
    "scvelo": "[Python Package] A tool for RNA velocity analysis.",
    "gseapy": "[Python Package] A Python wrapper for Gene Set Enrichment Analysis.",
    "DESeq2": "[R Package] Differential gene expression analysis.",
    "edgeR": "[R Package] Empirical Analysis of Digital Gene Expression Data in R.",
    "limma": "[R Package] Linear Models for Microarray Data.",
    "harmony": "[R Package] A method for integrating and analyzing single-cell data.",
    "WGCNA": "[R Package] Weighted Correlation Network Analysis.",
    "gget": "[Python Package] A toolkit for accessing genomic databases.",
    "cooler": "[Python Package] Storage and analysis of Hi-C data.",
    "faiss-cpu": "[Python Package] A library for efficient similarity search and clustering of dense vectors.",
    "pyranges": "[Python Package] A Python package for interval manipulation with a pandas-like interface.",
    "umap-learn": "[Python Package] Uniform Manifold Approximation and Projection, a dimension reduction technique.",
    "Matrix": "[R Package] A package that provides classes and methods for dense and sparse matrices.",
    "clusterProfiler": "[R Package] A package for statistical analysis and visualization of functional profiles for genes and gene clusters.",
    "dplyr": "[R Package] A grammar of data manipulation.",
    "ggplot2": "[R Package] A system for declaratively creating graphics.",
    "readr": "[R Package] A fast and friendly way to read rectangular data like CSV and TSV.",
    "stringr": "[R Package] A cohesive set of functions designed to make working with strings easier.",
    "tidyr": "[R Package] A package that helps create tidy data.",
}
